### ISSUE TITLE
GM_getValue is undefined

### ISSUE THREAD

**Issue by perrinaz** [SN-Koarashi/ig-helper#1]
Clicking the button does not cause download.  In the developers console, I see the message "GM_getValue is undefined"

Firefox: 113.0.2 (64bit)
Greasemonkey: 4.11

**Comment by SN-Koarashi** [comment]
Please make sure that you are using version 2.5.6.2 and it was downloaded from Greasyfork. This script is better compatible with the Tampermonkey extension and we recommend using it as the way to install the script.
