### ISSUE TITLE
[Enhance Feature Request] instagram video custom volume

### ISSUE THREAD

**Issue by Yomisana** [SN-Koarashi/ig-helper#12]
[Template Video of Instagram](https://www.instagram.com/p/C1yZMz8uxXH/)

Like Video right bottom have volume button it only mute and unmute, it may this script make it can custom Instagram this obj dom can custom on this tab video volume it really like youtube video had make user to custom volume? thx 😸

**Comment by SN-Koarashi** [comment]
You can use this setting to modify video volume
![image](https://github.com/SN-Koarashi/ig-helper/assets/40320172/4bf80ef3-c7ae-4182-8a70-18dbeecef6cf)

**Comment by Yomisana** [comment]
is possible be like this screenshot not in settings?
![chrome_dikLBmIqqa](https://github.com/SN-Koarashi/ig-helper/assets/93663341/69784bed-dc5b-4457-a65b-23ff94f7fef5)

**Comment by SN-Koarashi** [comment]
Here it come

**Comment by Yomisana** [comment]
How to use it? have any video seems 2.26.1 not working

**Comment by SN-Koarashi** [comment]
move your mouse to video volume in reels page
![image](https://github.com/user-attachments/assets/e54abf15-22df-4686-8cff-b73616fd5507)

**Comment by Yomisana** [comment]
I see it only work on ``https://www.instagram.com/reels``
else have audio button not support yet

5026 ***@***.***> 於 2024年7月27日 週六 下午10:22寫道：

**Comment by SN-Koarashi** [comment]
yes

**Comment by Yomisana** [comment]
In future will support all? thx

**Comment by SN-Koarashi** [comment]
Yes, but it needs more testing before rolling it out, so it will take some time

**Comment by Yomisana** [comment]
Ok, thanks for the update. 🚀

**Comment by SN-Koarashi** [comment]
The volume slider has been added to the post video. @Yomisana

**Comment by SN-Koarashi** [comment]
There has been no response to the issue for a long time and the function has been implemented.
