### ISSUE TITLE
[bug] Carousel post counter is sometimes not modified

### ISSUE THREAD

**Issue by sn-o-w** [SN-Koarashi/ig-helper#18]
There's a problem in the user script and I'm not sure what is wrong.

It's easy to reproduce this:
1. Open the Instagram homepage.
2. Hover on any carousel post, that has multiple resources (at this point, the counter's position is okay and updated to not interfere with IG-Helper buttons)
3. Open any story from the homepage (it doesn't matter if the story is opened from the Stories section or by clicking on any user's avatar in a regular post from the homepage)
4. Close the story.
5. Hover again on any carousel post, and notice the counter's position is no longer modified.

@SN-Koarashi Any idea?! 🤔

**Comment by SN-Koarashi** [comment]
The counter element is regenerated when returning to the page, which causes this issue.

**Comment by SN-Koarashi** [comment]
You can now check again to see if the issue still exists. @sn-o-w
