### ISSUE TITLE
[bug] Buttons not spawn sometimes

### ISSUE THREAD

**Issue by sn-o-w** [SN-Koarashi/ig-helper#19]
Sometimes, buttons don't spawn if you are on the Instagram homepage, then scroll down the page, and afterwards press the comment icon on a post.

Have a look:

https://github.com/user-attachments/assets/551e7fcb-6cdb-4f19-bc66-740799eb2ad6

It might be tricky and not always happening this behavior, but at least it fixes itself on the 2nd try. 🤔

Try at least to open 5-10 different posts in the foreground from the homepage.

**Comment by SN-Koarashi** [comment]
This may be due to network speed causing the dialog box window to appear after the function call.

**Comment by SN-Koarashi** [comment]
The problem may have been fixed, you can check if it still exists. @sn-o-w
