### ISSUE TITLE
Download button don't show in stories highlight (Continue from greasy fork )

### ISSUE THREAD

**Issue by DiceMast3r** [SN-Koarashi/ig-helper#3]
from https://greasyfork.org/en/scripts/404535-ig-helper/discussions/212935

Here a DOM code. 

[DOM.txt](https://github.com/SN-Koarashi/ig-helper/files/13461843/DOM.txt)

**Comment by SN-Koarashi** [comment]
The issue may have been fixed, please update the script to a new version to see if it is fixed.

**Comment by DiceMast3r** [comment]
Still not work. there a button but nothing happen when click and layout is broke (see screenshot and video).  

![Screenshot 2023-11-25 035108](https://github.com/SN-Koarashi/ig-helper/assets/42872837/91187d34-b222-45d8-9a16-ac06ad7186a6)


https://github.com/SN-Koarashi/ig-helper/assets/42872837/1c0b53e2-0f66-462d-979f-3da73d8c4565

**Comment by SN-Koarashi** [comment]
I have released a new update, please update the script again and check if the problem exists

**Comment by DiceMast3r** [comment]
Still not work. layout is bug more than previous version.

**Comment by SN-Koarashi** [comment]
> Still not work. layout is bug more than previous version.

Do you mean the current version will break your layout?

**Comment by DiceMast3r** [comment]
yeah like a previous version. 


https://github.com/SN-Koarashi/ig-helper/assets/42872837/20774c63-da4b-4a2f-87df-6af4258f0686

**Comment by SN-Koarashi** [comment]
IWhen I switched to another account of mine, my page had a layout similar to yours, so I started intensive testing and finally got something that worked fine for me.
Please update the script again and check if the problem persists.

**Comment by DiceMast3r** [comment]
It's work now. ⸂⸂⸜(രᴗര๑)⸝⸃⸃  thx for your work

**Comment by SN-Koarashi** [comment]
Thank you for your patient feedback to bring a better experience to this script.
