### ISSUE TITLE
Download Button Missing

### ISSUE THREAD

**Issue by BlazeFTL** [SN-Koarashi/ig-helper#30]
I Am On Firefox Android Nightly Latest 
Latest Script From GreasyFork

No Button From This UserScript Can Be Seen In Post...But Going Desktop Fixes The Issue...

[ScreenRecord](https://github.com/user-attachments/assets/ffa9e9b1-e78b-45dc-b714-b7a472f45b57)

Although I Do See The Buttons Maybe In 10% Post But In Most Places Its Not Appearing

**Comment by BlazeFTL** [comment]
Debug Info
On Destop Mode Where Buttons Do Appear [DOMTree.txt](https://github.com/user-attachments/files/16565853/DOMTree.txt)

On Non-Desktop Mode Where No Button Appears
[DOMTree(1).txt](https://github.com/user-attachments/files/16565860/DOMTree.1.txt)

**Comment by SN-Koarashi** [comment]
In fact, my script was not debugged for the mobile version of the page, but the problem you pointed out seems to be easy to solve. 
I switched to the mobile version of the page through the DevTools of the desktop version of the browser for testing, and it worked normally. 
You can use the latest version to try it.

**Comment by BlazeFTL** [comment]
Fixed❤️🔥

**Comment by BlazeFTL** [comment]
@SN-Koarashi For Mobile reels page button is still missing
Fix add
```
body > div[id^="mount"] section nav + div > div > article,
```
After
body > div[id^="mount"] section nav + div > article,
