### ISSUE TITLE
Here is the Info, I hope you can fix the issue

### ISSUE THREAD

**Issue by thinkpad4** [SN-Koarashi/ig-helper#4]
@SN-Koarashi Here is the dom from a IG story [DOM.txt](https://github.com/SN-Koarashi/ig-helper/files/13629843/DOM.txt)

**Comment by SN-Koarashi** [comment]
The DOM tree given in your file does not seem to be complete?
Please re-upload a file containing the complete DOM tree, and if possible, record the entire operation process in which you cannot see the download button as a video for me.

**Comment by thinkpad4** [comment]
@SN-Koarashi I see the download button, it just doesn't do anything when I click it.

**Comment by thinkpad4** [comment]
I do indeed https://i.imgur.com/FkosCrI.jpg

**Comment by SN-Koarashi** [comment]
This looks like the new layout, can you upload the full DOM tree?

**Comment by thinkpad4** [comment]
@SN-Koarashi [DOM.txt](https://github.com/SN-Koarashi/ig-helper/files/13643057/DOM.txt)  This should be all of it, This is EVERYTHING that the Alt Z showed

**Comment by SN-Koarashi** [comment]
The issue may have been fixed, please update the script and try again.

**Comment by thinkpad4** [comment]
WORKS!  Thank you very much
