### ISSUE TITLE
Video controller enhancment and minor bugs

### ISSUE THREAD

**Issue by marione44** [SN-Koarashi/ig-helper#41]
First of all, awesome work!

I use the "Display HTML5 Video Controller" a lot, but it has a downside: you can't click on tagged people since the video controller is above it. Is it possible to do something like what you did in issue #12? That would look cool and be more useful. Can this feature be implemented for stories as well? I have another script to enable the video controller, but I'd prefer to have everything in one script.

![ezgif com-animated-gif-maker](https://github.com/user-attachments/assets/6029cb4a-0273-46df-8966-3cc5b1c47b2b)

Now, I'll list some of the weird behaviors I've encountered so far:

- The icon to download the profile picture doesn't appear; however, if I change the container, it will appear. I use Firefox Multi-Account Containers. 
![Screenshot from 2024-11-07 17-55-41](https://github.com/user-attachments/assets/9aeef4f7-f053-47a8-9042-982889cdddeb)
![Screenshot from 2024-11-07 17-52-05](https://github.com/user-attachments/assets/1bf9c7d3-453d-492e-811f-460ced452e6f)

- I've set the video volume to a relatively low level. Even though it's not specified in the command description, it still works for stories. However, if you watch Bob's second story, then go to the next or previous one, or someone else's story, and then return to Bob's second story, the volume will increase, not respecting the value set.

I'm on ubuntu, i use firefox and violentmonkey.

**Comment by SN-Koarashi** [comment]
> First of all, awesome work!
> 
> I use the "Display HTML5 Video Controller" a lot, but it has a downside: you can't click on tagged people since the video controller is above it. Is it possible to do something like what you did in issue #12? That would look cool and be more useful. Can this feature be implemented for stories as well? I have another script to enable the video controller, but I'd prefer to have everything in one script.

Are you referring to applying the default custom volume bar to the story?

> The icon to download the profile picture doesn't appear; however, if I change the container, it will appear. I use Firefox Multi-Account Containers.

Layout updates or A/B testing will cause Instagram to apply different layouts. This issue is actually difficult for me to correct.

> I've set the video volume to a relatively low level. Even though it's not specified in the command description, it still works for stories. However, if you watch Bob's second story, then go to the next or previous one, or someone else's story, and then return to Bob's second story, the volume will increase, not respecting the value set.

The audio observer has been added in the latest version to reduce the frequency of such events. You can try again to see if the problem still exists.

**Comment by marione44** [comment]
> Are you referring to applying the default custom volume bar to the story?

What i meant is if its possible to have a custom bar to control the video instead of using the html5 video controller, so we can actually click on tagged people.
Regards to stories, adding a volume bar or even better a bar to control the video player would be a great feature.
Thank you

**Comment by SN-Koarashi** [comment]
> What i meant is if its possible to have a custom bar to control the video instead of using the html5 video controller, so we can actually click on tagged people. Regards to stories, adding a volume bar or even better a bar to control the video player would be a great feature.

I understand, I will study to see how to implement it

**Comment by SN-Koarashi** [comment]
Now you can find the volume slider in stories or highlights and adjust it on the fly. In addition, you can also toggle the display of HTML5 video controllers by right-clicking in video posts.
@marione44

**Comment by marione44** [comment]
Amazing work! Thank you so much, works perfectly. Last thing from me, is possible to extend this feature 

> toggle the display of HTML5 video controllers by right-clicking

 to stories as well? If HTML5 controller is active reply box, like and direct button should be hidden, im talking about stories.

**Comment by SN-Koarashi** [comment]
> to stories as well? If HTML5 controller is active reply box, like and direct button should be hidden, im talking about stories.

Not a bad idea, I'll try it out and see if I can apply it to the story.

**Comment by SN-Koarashi** [comment]
> to stories as well? If HTML5 controller is active reply box, like and direct button should be hidden, im talking about stories.

Hi there, @marione44, HTML5 controller should be supported now

**Comment by marione44** [comment]
> I tried to replicate this in Firefox, but I couldn't. Perhaps share the whole DOM tree? 🤔

Probably as SN-Koarashi said its something relative to A/B testing. It's not a problem that bothers me, however if you are still interest i can share the DOM tree.

@SN-Koarashi The HTML5 controller works but i noticed that when i toggle it off, lets say to reply a story, the volume slider its not functional anymore. This happens only in the stories

**Comment by SN-Koarashi** [comment]
> The HTML5 controller works but i noticed that when i toggle it off, lets say to reply a story, the volume slider its not functional anymore. This happens only in the stories

🤔 Are you talking about the custom volume slider, or the volume adjustment in the HTML5 controller?

**Comment by marione44** [comment]
I have html5 controller active, when i toggle it off the custom volume slider is missing. Only stories are affected

**Comment by SN-Koarashi** [comment]
> I have html5 controller active, when i toggle it off the custom volume slider is missing. Only stories are affected

You said that after turning off the setting of the HTML5 volume controller, the custom volume slider was lost; instead of being automatically replaced with a custom volume slider like in the post?

**Comment by marione44** [comment]
> You said that after turning off the setting of the HTML5 volume controller, the custom volume slider was lost; instead of being automatically replaced with a custom volume slider like in the post?

When the HTML5 controller is disabled in the settings, the custom volume slider is available in stories, right? However, if HTML5 is enabled and you need to reply, you have to turn it off not from the settings but by right-clicking. In this case, the custom volume slider should be present again

**Comment by SN-Koarashi** [comment]
> When the HTML5 controller is disabled in the settings, the custom volume slider is available in stories, right? However, if HTML5 is enabled and you need to reply, you have to turn it off not from the settings but by right-clicking. In this case, the custom volume slider should be present again

It should now behave consistent with posts/reels.

**Comment by marione44** [comment]
> It should now behave consistent with posts/reels.
> NOTE: This has modifications to the stylesheet, which may cause the story and highlight volume sliders to disappear/not work since the style.css cache is in the extension.

On my end, it's not working. To be fair, it's not a big deal. I want to address that this new update broke the custom volume slider functionality when the HTML5 controller is disabled in the settings. Again, only stories seem to be affected. You can revert the update to the previous version and close the issue if it's a hassle for you, since the main issue has been addressed

**Comment by SN-Koarashi** [comment]
If this update (7bf870594b786dbf00ca3571ecd675391e40982a) causes the previously visible custom volume slider to become invalid (for example, after turning off the settings of the HTML5 controller), it may be because the style sheet is still cached and has not been updated. If you do not want to wait for it to automatically update, You need to refresh the stylesheet manually.

**Comment by marione44** [comment]
> you need to manually refresh the stylesheet

I did it, now everything is running smoothly. I had to remove the script and reinstall it, updating it only wasn't enough.
For me the issue is solved, i dont know if i have to close it or not.

@sn-o-w 
[DOMTree-1732483295204.txt](https://github.com/user-attachments/files/17895087/DOMTree-1732483295204.txt)

**Comment by marione44** [comment]
> Change all occurences of **`header > section:first img[alt]`** to **`header > *[class]:first-child img[alt]`**

It works, thank you both of you for the support
