### ISSUE TITLE
[Bug?] Media API is no longer downloading images in highest resolution

### ISSUE THREAD

**Issue by WanHaes** [SN-Koarashi/ig-helper#47]
I was using IG Helper for quite a while with these options:

<details>

<summary>Options</summary>

![2024-11-28_21-58-37](https://github.com/user-attachments/assets/bf5fcd4d-53ca-41a0-a841-23592123ff22)

</details>

Now I happened to notice that images are downloaded in 1080x1350 instead of possible 1440x1800. If "Force fetch resource via Media API" is disabled then the images are downloaded in 1440x1800. I checked my previous downloads from Instagram with IG Helper (via Media API) and there are 1440x1800 images which been dowloaded just a few day ago. I've now tried to download the same recent picture, and it is in 1080x1350. Uncheck Media API – and it downloads in 1440x1800.

**Comment by SN-Koarashi** [comment]
Can you post the DOM Tree? I need to check the logs to confirm the issue.

You need to first open a new tab and enter instagram, and then download the same resource with and without the Media API enabled.  Finally, export the DOM Tree through the debug window of ALT+Z.

**Comment by WanHaes** [comment]
Uh, sorry for silence.

Seems like this issue doesn't persist anymore, at least I can't reproduce it. When I looked at the DOM tree via devtools about a month ago, there was only one "source" link with 1080x1350 image. Now there're many links – with source (actual source), 1080x, 720x and so on.

But, now I'm facing another issue. Some images are downloaded in square while source image is not a square. Here's an example (same result with and without the Media API enabled): [DOMTree-1734977811880.txt](https://github.com/user-attachments/files/18232306/DOMTree-1734977811880.txt)

**Comment by SN-Koarashi** [comment]
Thank you for providing a good example. I checked the logs and found that the largest image returned by the API is 1080x1080, but after actual access, it only returns 960x960. This is indeed strange.

**Comment by SN-Koarashi** [comment]
291927804c211d91af2a05ae71c1a65f6d4a62aa
I've changed the sorting method and should now be able to correctly get the highest resolution image (via MediaAPI)
