### ISSUE TITLE
Sorry but i cannot download in stories

### ISSUE THREAD

**Issue by jiyi-jiyi** [SN-Koarashi/ig-helper#5]
I see the download button, it just doesn't do anything when I click it.
version            2.12.1
[DOMTree.txt](https://github.com/SN-Koarashi/ig-helper/files/13662205/DOMTree.txt)

**Comment by SN-Koarashi** [comment]
The issue should have been fixed, please update the script and try again

**Comment by thinkpad4** [comment]
@SN-Koarashi Please undo whatever you changed, I can't download stories anymore

**Comment by SN-Koarashi** [comment]
@thinkpad4 You mean you can't download photos from stories?

**Comment by SN-Koarashi** [comment]
I've added a fallback universal method for fetching photo links for stories, please update your script and try again.
@thinkpad4

**Comment by thinkpad4** [comment]
Works again!!!!!  Thank you very much

**Comment by SN-Koarashi** [comment]
Since the initiator did not reply, the issue will be considered resolved.
