### ISSUE TITLE
Getting a message that pops up saying max button creation

### ISSUE THREAD

**Issue by thinkpad4** [SN-Koarashi/ig-helper#7]
@SN-Koarashi I saw this: [Added button creation maximum try times.](https://github.com/SN-Koarashi/ig-helper/commit/7bc28b088ae5b91f4e37e409d79c4e8ac30896a9) and it's causing a prompt that doesn't go away talking about max button creation.  This is what it says, Trying to call button creation method reached to maximum try times. If you want to re-register method, please open script menu and press "Reload Script" button or hotkey "R" to reload main timer.  Is it possible to remove this button creation feature please?   When I get that popup I can't access the settings menu or the reload script option as they don't show.  Thank you very much

**Comment by SN-Koarashi** [comment]
The reload script option is available in the script drop-down menu that appears after clicking on the extension.
Also, could you please explain the timing when this pop-up window appears?

@thinkpad4

**Comment by SN-Koarashi** [comment]
![Screenshot_2024-03-06-11-09-38-188_com.android.chrome~3.jpg](https://github.com/SN-Koarashi/ig-helper/assets/40320172/30a40536-b100-4bb2-8917-c35e8dad7dc6)

**Comment by thinkpad4** [comment]
@SN-Koarashi I know that, but when I get the dialog box saying that I've reached the max button creation I can't clear it, I keep clicking OK and it just returns, and while it's showing I can't access the dropdown menu.  Let me get a screenshot

**Comment by SN-Koarashi** [comment]
@thinkpad4 

I see you're using Violentmonkey, and according to another previous user, this extension has some issues with clearInterval.

https://github.com/violentmonkey/violentmonkey/issues/2042

**Comment by thinkpad4** [comment]
@SN-Koarashi Is there a way to make your script work in violentmonkey?  I have a lot of scripts and violentmonkey is very lightweight compared to tampermonkey

**Comment by SN-Koarashi** [comment]
@thinkpad4 
You can try updating your extended version and make sure that this script is actually loaded as document-idle (i.e. the default)

**Comment by thinkpad4** [comment]
@SN-Koarashi I have a solution for the time being, I'll use violentmonkey for all my scripts, EXCEPT this one, i'll install this only only on tampermonkey

**Comment by SN-Koarashi** [comment]
Does the problem still occur when you change the load timing in the script settings to document-idle or the default value?
@thinkpad4

**Comment by SN-Koarashi** [comment]
And is the console still outputting content without the page scroller moving?

**Comment by thinkpad4** [comment]
It looks like Violentmonkey 2.18.1beta has fixed the issue.  https://github.com/violentmonkey/violentmonkey/commit/6fb2544af4e8249dd5c0e1a3c3e1676f2d048fe4

**Comment by SN-Koarashi** [comment]
Does the issue still persist when you update to version 2.18.1beta?

**Comment by thinkpad4** [comment]
It does NOT

**Comment by SN-Koarashi** [comment]
It appears that the issue can be considered resolved if the situation no longer occurs.

**Comment by thinkpad4** [comment]
Thank you for you help, I'll close this now

**Comment by SN-Koarashi** [comment]
@sn-o-w 
Does the window disappear after clicking OK? Or does it appear multiple times?

In addition, you can update the script to the latest version. In the latest version, when the termination condition is reached, only a warning will be displayed on the console and no alert window will appear.

**Comment by SN-Koarashi** [comment]
If you update to 2.18.1 BETA, this warning may still appear. When you click on a post on your profile page, it appears as a float (called a modal or dialog). 
At this point, if you press ESC or click elsewhere, this problem may still occur if you close the window quickly enough. This is caused by the execution interval of the timer in the script being slower than the rate at which you turn it off.

**Comment by thinkpad4** [comment]
@SN-Koarashi I'm not getting the warning anymore on 2.18.1 Beta, and the rare time I lose the buttons now the Alt+R brings them right back.

**Comment by SN-Koarashi** [comment]
@thinkpad4 
Missing buttons are an occasional issue. My guess is that when the timer detects the element, although the Instagram element has already appeared, this element is an old element, not a new one (non-synchronous loading). This problem is unavoidable (at least I haven't found a solution yet). It used to be possible to refresh the entire page with F5 to solve the problem, but this was too slow, so I added the function of reloading the main timer.
