### ISSUE TITLE
不知道如何调节音量

### ISSUE THREAD

**Issue by dragonaptx4869** [SN-Koarashi/ig-helper#9]
设置里开启了调节音量，右键都按烂了都没看见哪里可以调节

**Comment by SN-Koarashi** [comment]
你可以在右擊設置的文字上按下右鍵，他應該會出現如第二張圖的樣子
![image](https://github.com/SN-Koarashi/ig-helper/assets/40320172/a2bb0695-b2f4-41e7-b152-26b30038e546)
![image](https://github.com/SN-Koarashi/ig-helper/assets/40320172/d943f356-550b-457e-878e-ba9b672d5c76)
